/* ---------------------------------------------------------------------------------
   file-start: js/ads/axz.min.js 
*/

﻿SCDoumentReqeustTime=(new Date).getTime();var organicArrays={timingArrayOfResult:[],startTimeArray:[],endTimeArray:[],errorListArray:[]},organicDocInfo={currentDocumentRequestTime:-1,currentDocumentSize:-1,documentLastModDate:(new Date).getTime()};
try{var axzNT={variables:{pageLoadTime:-1,pageLoadTimeResult:-1,redirect:-1,redirectResult:-1,connectTime:-1,connectTimeResult:-1,domainTime:-1,domainTimeResult:-1,secureTime:-1,secureTimeResult:-1,requestTime:-1,requestTimeResult:-1,responseTime:-1,responseTimeResult:-1,domInteractiveTime:-1,domInteractiveTimeResult:-1,documentLoadTime:-1,documentLoadTimeResult:-1},NavigationTimingObj:null,isNavigationEnabled:!1,ifSupportNavigationTiming:function(){try{if(window.performance.timing)return axzNT.NavigationTimingObj=
window.performance.timing,!0;if(window.mozPerformance.timing)return axzNT.NavigationTimingObj=window.msPerformance.timing,!0;if(window.webkitPerformance.timing)return axzNT.NavigationTimingObj=window.webkitPerformance.timing,!0;axzNT.NavigationTimingObj=null;return!1}catch(a){return axzNT.NavigationTimingObj=null,!1}},pageLoadingTime:function(){try{return axzNT.variables.pageLoadTime=-1,axzNT.variables.pageLoadTimeResult=axzNT.NavigationTimingObj.loadEventEnd-axzNT.NavigationTimingObj.navigationStart,
0<=axzNT.variables.pageLoadTimeResult?axzNT.variables.pageLoadTimeResult:axzNT.variables.pageLoadTime}catch(a){organicArrays.errorListArray.push("pageLoadingTime:"+a)}},redirectTime:function(){try{return axzNT.variables.redirect=-1,axzNT.variables.redirectResult=axzNT.NavigationTimingObj.redirectEnd-axzNT.NavigationTimingObj.redirectStart,0<=axzNT.variables.redirectResult?axzNT.variables.redirectResult:axzNT.variables.redirect}catch(a){organicArrays.errorListArray.push("redirectTime:"+a)}},connection:function(){try{return axzNT.variables.connectTime=
-1,axzNT.variables.connectTimeResult=axzNT.NavigationTimingObj.connectEnd-axzNT.NavigationTimingObj.connectStart,0<=axzNT.variables.connectTimeResult?axzNT.variables.connectTimeResult:axzNT.variables.connectTime}catch(a){organicArrays.errorListArray.push("connection:"+a)}},dns:function(){try{return axzNT.variables.domainTime=-1,axzNT.variables.domainTimeResult=axzNT.NavigationTimingObj.domainLookupEnd-axzNT.NavigationTimingObj.domainLookupStart,0<=axzNT.variables.domainTimeResult?axzNT.variables.domainTimeResult:
axzNT.variables.domainTime}catch(a){organicArrays.errorListArray.push("connection:"+a)}},ssl:function(){try{return axzNT.variables.secureTime=-1,0<axzNT.NavigationTimingObj.secureConnectionStart?(axzNT.variables.secureTimeResult=axzNT.NavigationTimingObj.requestStart-axzNT.NavigationTimingObj.secureConnectionStart,0<=axzNT.variables.secureTimeResult?axzNT.variables.secureTimeResult:axzNT.variables.secureTime):axzNT.variables.secureTime}catch(a){organicArrays.errorListArray.push("ssl:"+a)}},request:function(){try{return axzNT.variables.requestTime=
-1,axzNT.variables.requestTimeResult=axzNT.NavigationTimingObj.responseStart-axzNT.NavigationTimingObj.requestStart,0<=axzNT.variables.requestTimeResult?axzNT.variables.requestTimeResult:axzNT.variables.requestTime}catch(a){organicArrays.errorListArray.push("request:"+a)}},response:function(){try{return axzNT.variables.responseTime=-1,axzNT.variables.responseTimeResult=axzNT.NavigationTimingObj.responseEnd-axzNT.NavigationTimingObj.responseStart,0<=axzNT.variables.responseTimeResult?axzNT.variables.responseTimeResult:
axzNT.variables.responseTime}catch(a){organicArrays.errorListArray.push("response:"+a)}},documentLoadTime:function(){try{return axzNT.variables.documentLoadTime=-1,axzNT.variables.documentLoadTimeResult=axzNT.NavigationTimingObj.responseEnd-axzNT.NavigationTimingObj.requestStart,0<=axzNT.variables.documentLoadTimeResult?axzNT.variables.documentLoadTimeResult:axzNT.variables.documentLoadTime}catch(a){organicArrays.errorListArray.push("documentLoadTime:"+a)}},domInteractive:function(){try{return axzNT.variables.domInteractiveTime=
-1,axzNT.variables.domInteractiveTimeResult=axzNT.NavigationTimingObj.domInteractive-axzNT.NavigationTimingObj.domLoading,0<=axzNT.variables.domInteractiveTimeResult?axzNT.variables.domInteractiveTimeResult:axzNT.variables.domInteractiveTime}catch(a){organicArrays.errorListArray.push("domInteractive:"+a)}}};axzNT.isNavigationEnabled=axzNT.ifSupportNavigationTiming()}catch(err$$10){var errorToString="axzNT:"+err$$10;organicArrays.errorListArray.push(errorToString)}
var organicUrlFuns={ifRelativeUrl:function(a){try{return-1!=a.indexOf(window.location.hostname)?!0:!1}catch(b){organicArrays.errorListArray.push("ifRelativeUrl")}},rel_to_abs:function(a){try{if(/^(https?|file|ftps?):/.test(a))return a;var b=location.href.match(/^(.+)\/?(?:#.+)?$/)[0]+"/";if("/"==a.charAt(0))return location.protocol+"//"+location.host+a;if("/"!=a.charAt(0)&&"."!=a.charAt(0))return document.URL.slice(0,document.URL.lastIndexOf("/"))+"/"+a;if("./"==a.substring(0,2))a="."+a;else{if(/^\s*$/.test(a))return b;
a="../"+a}for(a=b+a;/\/\.\.\//.test(a=a.replace(/[^\/]+\/+\.\.\//g,"")););return a=a.replace(/\.\//g,"")}catch(c){organicArrays.errorListArray.push("rel_to_abs")}}},organicListeners={addlistener:function(){if(4==this.readyState)try{var a=this.url;organicArrays.endTimeArray[a]=(new Date).getTime();if(this.contentLength=this.getResponseHeader("Content-Length"))this.contentLength=this.contentLength.toString().split(" ").join("");if(this.contentType=this.getResponseHeader("Content-Type"))this.contentType=
this.contentType.toString().split(" ").join("");this.getResponseHeader("Last-Modified")?this.contentLastMod=organic.ParseDateMod(this.getResponseHeader("Last-Modified")):this.contentLastMod=0;if(a.split("?")[0]==document.location.href)this.contentLength&&(organicDocInfo.currentDocumentSize=this.contentLength.toString().split(" ").join("")),organic.currentDcoumentLastMod=this.contentLastMod,organicDocInfo.currentDocumentRequestTime=organicArrays.endTimeArray[a]-organicArrays.startTimeArray[a];else{null==
this.contentLastMod&&(this.contentLastMod=0);var b={url:escape(organicUrlFuns.rel_to_abs(a)),timing:organicArrays.endTimeArray[a]-organicArrays.startTimeArray[a],type:this.contentType,startTime:organicArrays.startTimeArray[a],end_time:organicArrays.endTimeArray[a],cont_length:this.contentLength,last_mod:this.contentLastMod,code:this.status};organicArrays.timingArrayOfResult.push(b)}}catch(c){organicArrays.errorListArray.push("addlistener")}}},organic={Handlers:{HTTPSHandler:"https://beacon.nccgroup-webperf.com/AsyncHandler.ashx",
HTTPHandler:"http://beacon.nccgroup-webperf.com/AsyncHandler.ashx"},IfHTTPS:function(){return"https:"==location.protocol?organic.Handlers.HTTPSHandler:organic.Handlers.HTTPHandler},Setting:{clientId:"SUP001",jsVersion:1.1,isEnableOnTimePlan:!1,domUpdatingTiming:!1,isXMLTimingMethodEnabled:!1,isFormCaptureEnabled:!1,isHtmlCaptureEnabled:!1,backupTimingEnabled:!1,isBriefCaputreEnabled:!0,isWrapperEnable:!1,crossDomainPostEnabled:!0,crossDomainXmlHttpReq:!1,serverHandler:function(){return organic.IfHTTPS()},
expireSetting:10},isSummarySubmitted:!1,utcTime:(new Date).getTimezoneOffset(),currentPageRequestTime:SCDoumentReqeustTime,currentPageLoadingTime:SCDoumentReqeustTime,clientLeaveTime:SCDoumentReqeustTime,rootUrl:document.location.href,cookieSessionID:new String,cookieStepNum:1,isBeforeUnload:!1,SetBeforeUnload:function(){window.addEventListener&&window.addEventListener("beforeunload",function(a){organic.isBeforeUnload=!0;organic.ReadyToSubmit()})},DOM:{DOMLoaded:!1,DOMHasLoaded:function(){try{organic.DOM.DOMLoaded||
"t"==organic.Cookies.ifStop()||(organic.updateLoadingTime(),organic.updateLeaveTime(),organic.DOM.DOMLoaded=!0,!1==organic.isBeforeUnload&&organic.SetBeforeUnload(),OrganicFormData.retrieveFormAndHtml(),organic.Process.BackUpPlan(),window.addEventListener?window.addEventListener("load",organic.ReadyToSubmit,!1):window.attachEvent?window.attachEvent("onload",organic.ReadyToSubmit):window.onLoad&&(window.onload=organic.ReadyToSubmit))}catch(a){organicArrays.errorListArray.push("DOMHasLoaded")}},DOMReady:function(){try{document.addEventListener&&
document.addEventListener("DOMContentLoaded",organic.DOM.DOMHasLoaded,!1),/KHTML|WebKit|iCab/i.test(navigator.userAgent)&&(DOMLoadTimer=setInterval(function(){/loaded|complete/i.test(document.readyState)&&(organic.DOM.DOMHasLoaded(),clearInterval(DOMLoadTimer))},10)),document.all&&!window.opera&&(document.write('<script type="text/javascript" id="SCContentLoadtag" defer="defer" src="">\x3c/script>'),document.getElementById("SCContentLoadtag").onreadystatechange=function(){"complete"==this.readyState&&
organic.DOM.DOMHasLoaded()}),window.addEventListener?window.addEventListener("load",organic.DOM.DOMHasLoaded,!1):window.attachEvent?window.attachEvent("onload",organic.DOM.DOMHasLoaded):window.onLoad&&(window.onload=organic.DOM.DOMHasLoaded)}catch(a){organicArrays.errorListArray.push("DOMReady")}}},DocumentReferrer:function(){var a="";try{document.referrer&&(a=document.referrer)}catch(b){organicArrays.errorListArray.push("DocumentReferrer"),a=""}finally{return a}},ConvertUrl:function(a){try{for(var b=
location.href,b=b.substring(0,b.lastIndexOf("/"));/^\.\./.test(a);)b=b.substring(0,b.lastIndexOf("/")),a=a.substring(3);return b+"/"+a}catch(c){organicArrays.errorListArray.push("ConvertUrl")}},ClientSystemInfo:function(){try{this.browser=this.SearchString(this.dataBrowser)||"An unknown browser",this.version=this.SearchVersion(navigator.userAgent)||this.SearchVersion(navigator.appVersion)||"an unknown version",this.OS=navigator.userAgent||"an unknown OS"}catch(a){organicArrays.errorListArray.push("ClientSystemInfo")}finally{return{OS:this.OS,
Browser:this.browser,Version:this.version}}},SearchString:function(a){try{for(var b=0;b<a.length;b++){var c=a[b].string,d=a[b].prop;this.versionSearchString=a[b].versionSearch||a[b].identity;if(c){if(-1!=c.indexOf(a[b].subString))return a[b].identity}else if(d)return a[b].identity}}catch(e){organicArrays.errorListArray.push("SearchString")}},SearchVersion:function(a){try{var b=a.indexOf(this.versionSearchString);if(-1!=b)return parseFloat(a.substring(b+this.versionSearchString.length+1))}catch(c){organicArrays.errorListArray.push("SearchVersion")}},
dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,
subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],StartTimer:function(){return(new Date).getTime()},ParseDateMod:function(a){try{return a=null==a||0==a?0:Date.parse(a)}catch(b){return organicArrays.errorListArray.push("ParseDateMod"),
0}},ReadyToSubmit:function(){"t"!=organic.Cookies.ifStop()&&organic.SubmittingReport()},ifCrossDomainPost:function(){return organic.Setting.crossDomainPostEnabled?organic.IfCrossDomain():!1},packetId:0,jsonBuilder:{jsonHtmlDataBuilder:function(a,b){a.HD=b;return a},jsonFormDataBuilder:function(a,b){a.FD=b;return a},jsonPacketNumberBuilder:function(a,b){a.PacketId=b;return a},jsonNavigationBuilder:function(a,b,c,d,e,f,g,h){a.DNS=b;a.CO=c;a.SSL=d;a.REQ=e;a.RES=f;a.DI=g;a.RT=h;return a},jsonParentPageBuilder:function(a,
b){b.parentPage=a;return b},jsonTimingResultBuilder:function(a,b){a.TimingResults=JSON.stringify(b);organicArrays.timingArrayOfResult=[];return a},jsonOverviewInfo:function(a,b,c,d,e,f,g,h,k,l,m,n,p,q,r,s,t){a.U=b;a.S=c;a.LT=d;a.CT=e;a.N=f;a.I=g;a.R=h;a.T=k;a.O=l;a.V=m;a.B=n;a.RQ=p;a.C=q;a.L=r;a.D=s;a.J=t;return a},jsonErrorReport:function(a,b){a.ErrorReport=b;return a}},preparePacketHeader:{UpdatePageTiming:function(){organic.currentPageLoadingTime<=organic.currentPageRequestTime&&organic.updateLoadingTime();
organic.currentPageLoadingTime>organic.clientLeaveTime&&organic.updateLeaveTime()},SetPageTiming:function(){axzNT.NavigationTimingObj.navigationStart&&(organic.currentPageRequestTime=axzNT.NavigationTimingObj.navigationStart);axzNT.NavigationTimingObj.loadEventEnd&&(organic.currentPageLoadingTime=axzNT.NavigationTimingObj.loadEventEnd);-1==organicDocInfo.currentDocumentRequestTime&&(organicDocInfo.currentDocumentRequestTime=axzNT.documentLoadTime())},Post:function(){var a={};"undefined"!==typeof axzNT&&
axzNT.isNavigationEnabled?(organic.preparePacketHeader.SetPageTiming(),a=organic.jsonBuilder.jsonNavigationBuilder(a,axzNT.dns(),axzNT.connection(),axzNT.ssl(),axzNT.request(),axzNT.response(),axzNT.domInteractive(),axzNT.redirectTime())):organic.preparePacketHeader.UpdatePageTiming();return a=organic.jsonBuilder.jsonOverviewInfo(a,escape(organic.rootUrl),organicDocInfo.currentDocumentSize,organicDocInfo.documentLastModDate,organicDocInfo.currentDocumentRequestTime,organic.cookieStepNum,organic.cookieSessionID,
escape(organic.DocumentReferrer()),organic.utcTime,escape(organic.ClientSystemInfo().OS),escape(organic.ClientSystemInfo().Version),escape(organic.ClientSystemInfo().Browser),organic.currentPageRequestTime,organic.currentPageLoadingTime,organic.clientLeaveTime,organic.Setting.clientId,organic.Setting.jsVersion)},Get:function(){var a="";"undefined"!==typeof axzNT&&null!=axzNT.NavigationTimingObj?(organic.preparePacketHeader.SetPageTiming(),a="DNS="+axzNT.dns()+"&CO="+axzNT.connection()+"&SSL="+axzNT.ssl()+
"&REQ="+axzNT.request()+"&RES="+axzNT.response()+"&DI="+axzNT.domInteractive()+"&RT="+axzNT.redirectTime(),a+="&"):organic.preparePacketHeader.UpdatePageTiming();return a=a+"U="+escape(organic.rootUrl)+" "+organicDocInfo.currentDocumentSize+" "+organicDocInfo.documentLastModDate+" "+organicDocInfo.currentDocumentRequestTime+"&N="+organic.cookieStepNum+"&I="+organic.cookieSessionID+"&R="+escape(organic.DocumentReferrer())+"&T="+organic.utcTime+"&O="+escape(organic.ClientSystemInfo().OS)+"&V="+escape(organic.ClientSystemInfo().Version)+
"&B="+escape(organic.ClientSystemInfo().Browser)+"&RQ="+organic.currentPageRequestTime+"&C="+organic.currentPageLoadingTime+"&L="+organic.clientLeaveTime+"&D="+organic.Setting.clientId+"&J="+organic.Setting.jsVersion}},preparePacketBody:{Empty:function(a){organic.packetId++;organic.CrossDomainCracker(organic.Setting.serverHandler(),a+"&PacketId="+organic.packetId)},Post:function(a,b){if(0<b)"undefined"!=organicArrays.timingArrayOfResult.length&&0<organicArrays.timingArrayOfResult.length&&null!=organicArrays.timingArrayOfResult.length&&
(a=organic.jsonBuilder.jsonTimingResultBuilder(a,organicArrays.timingArrayOfResult),organic.packetId++,a=organic.jsonBuilder.jsonPacketNumberBuilder(a,organic.packetId),organic.CrossDomainCracker(organic.Setting.serverHandler(),JSON.stringify(a)));else if(organic.isBeforeUnload||organic.Setting.isBriefCaputreEnabled)organic.isBeforeUnload=!1,organic.packetId++,a=organic.jsonBuilder.jsonPacketNumberBuilder(a,organic.packetId),organic.CrossDomainCracker(organic.Setting.serverHandler(),JSON.stringify(a))},
Get:function(a,b,c){for(var d="",e=1500-a.length;0<b;)if("undefined"!=organicArrays.timingArrayOfResult.length&&0<organicArrays.timingArrayOfResult.length&&null!=organicArrays.timingArrayOfResult.length){var f=organicArrays.timingArrayOfResult[0],g="",g=f.url;if(f){isNaN(f.timing)&&(!isNaN(f.startTime)&&isNaN(f.end_Time)?(f.timing=f.startTime-SCDoumentReqeustTime,f.end_Time=f.startTime,f.startTime=SCDoumentReqeustTime):isNaN(f.startTime)&&!isNaN(f.end_Time)&&(f.timing=f.end_Time-SCDoumentReqeustTime,
f.startTime=SCDoumentReqeustTime));organicUrlFuns.ifRelativeUrl(f.url)||(g=organicUrlFuns.rel_to_abs(f.url));var h=g,k="";1500<g.length?(g=h.split("?")[0],1500<g.length||(f.last_mod||(f.last_mod=0),k=g+" "+f.startTime+" "+f.end_time+" "+f.type+" "+c+" "+f.cont_length+" "+f.last_mod+" "+f.code+" ")):(f.last_mod||(f.last_mod=0),k=g+" "+f.startTime+" "+f.end_time+" "+f.type+" "+c+" "+f.cont_length+" "+f.last_mod+" "+f.code+" ");f=k.length;g=d.length;if(0==b){organic.packetId++;organic.CrossDomainCracker(organic.Setting.serverHandler(),
a+"&PacketId="+organic.packetId);break}else if(g+f>e){if(organic.packetId++,organic.CrossDomainCracker(organic.Setting.serverHandler(),a+"&TimingResult="+escape(d)+"&PacketId="+organic.packetId),organicArrays.timingArrayOfResult.splice(0,1),d=k,b=organicArrays.timingArrayOfResult.length,0==b){organic.packetId++;organic.CrossDomainCracker(organic.Setting.serverHandler(),a+"&TimingResult="+escape(d)+"&PacketId="+organic.packetId);break}}else if(0==organicArrays.timingArrayOfResult.length-1){d+=k;organic.packetId++;
organic.CrossDomainCracker(organic.Setting.serverHandler(),a+"&TimingResult="+escape(d)+"&PacketId="+organic.packetId);organicArrays.timingArrayOfResult.splice(0,1);break}else d+=k,organicArrays.timingArrayOfResult.splice(0,1),b=organicArrays.timingArrayOfResult.length}}}},packetStringHeader:function(a){try{return organic.ifCrossDomainPost()?organic.preparePacketHeader.Post(a):organic.preparePacketHeader.Get(a)}catch(b){organicArrays.errorListArray.push("packetStringHeader")}},packetStringBody:function(a,
b,c){try{organic.ifCrossDomainPost()?organic.preparePacketBody.Post(a,b):0==b&&!1==organic.isSummarySubmitted?(organic.isSummarySubmitted=!0,organic.preparePacketBody.Empty(a)):organic.preparePacketBody.Get(a,b,c)}catch(d){organicArrays.errorListArray.push("packetStringBody")}},errorPacketReporting:{POST:function(a){try{a=organic.jsonBuilder.jsonErrorReport(a,organicArrays.errorListArray),organic.packetId++,a=organic.jsonBuilder.jsonPacketNumberBuilder(a,organic.packetId),organic.CrossDomainCracker(organic.Setting.serverHandler(),
JSON.stringify(a)),organicArrays.errorListArray=[]}catch(b){organicArrays.errorListArray.push("errorPacketReportingPost")}},GET:function(a){try{var b=1500-a.length,c=organicArrays.errorListArray.length,d="";if(0<c)for(var e=0;e<c;e++){var f=organicArrays.errorListArray[e];f.length+d.length>b?(organic.packetId++,organic.CrossDomainCracker(organic.Setting.serverHandler(),a+"&Error_Report="+escape(d)+"&PacketId="+organic.packetId),d=f+";",organicArrays.errorListArray.splice(0,1)):e==c-1?(d=d+f+";",organicArrays.errorListArray.splice(0,
1),organic.packetId++,organic.CrossDomainCracker(organic.Setting.serverHandler(),a+"&Error_Report="+escape(d)+"&PacketId="+organic.packetId),d=""):(d=d+f+";",organicArrays.errorListArray.splice(0,1),c=organicArrays.errorListArray.length)}}catch(g){organicArrays.errorListArray.push("errorPacketReportingGet")}},Submit:function(a){try{0<organicArrays.errorListArray.length&&(organic.ifCrossDomainPost()?organic.errorPacketReporting.POST(a):organic.errorPacketReporting.GET(a))}catch(b){organicArrays.errorListArray.push("errorPacketReportingSubmit")}}},
SubmittingReport:function(){var a=organic.packetStringHeader();try{var b=organicArrays.timingArrayOfResult.length,c=escape(document.location.href);organic.packetStringBody(a,b,c);organic.errorPacketReporting.Submit(a)}catch(d){b=d.name.toString()+":"+d.message.toString(),c=(new Date).getTime(),organicArrays.errorListArray.push(b+","+c),organic.errorPacketReporting.Submit(a)}},ImageHandler:function(a){"Explorer"==organic.ClientSystemInfo().Browser?a.onreadystatechange=function(){"complete"==a.readyState&&
(-1==organicUrlFuns.rel_to_abs(a.src).indexOf(document.domain)&&organic.Setting.crossDomainXmlHttpReq?organic.ImageTimer(a.src):organic.Timing.Start(a.src))}:a.addEventListener("load",organic.NodeUpdateHandler,!1)},OrganicRequest:{Create:function(){try{var a=!1;if("file:"==location.protocol){if(!a)try{a=new ActiveXObject("MSXML2.XMLHTTP")}catch(b){a=!1}if(!a)try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(c){a=!1}}if(!a)try{a=new XMLHttpRequest}catch(d){a=!1}if("undefined"!=typeof ActiveXObject){if(!a)try{a=
new ActiveXObject("MSXML2.XMLHTTP")}catch(e){a=!1}if(!a)try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(f){a=!1}}if(!a)try{a=createRequest()}catch(g){a=!1}}catch(h){organicArrays.errorListArray.push("Create"),a=null}finally{return a}},Document:function(a){try{"t"!=organic.Cookies.ifStop()&&organic.Setting.isXMLTimingMethodEnabled&&organic.Timing.Start(a)}catch(b){organic.errorListArray.push("Document")}},Header:function(a){try{var b=new organic.OrganicRequest.Create;b.onreadystatechange=function(){if(4==
b.readyState){if(404==b.status&&(a.contentLength=b.getResponseHeader("Content-Length"),a.contentLength=a.contentLength.toString().split(" ").join(""),a.contentType=b.getResponseHeader("Content-Type"),a.contentType=a.contentType.toString().split(" ").join(""),a.contentLastMod=organic.ParseDateMod(b.getResponseHeader("Last-Modified")),a.contentLength&&a.contentType&&a.startTime)){a.loadingTime=a.finishTime-a.startTime;null==a.contentLastMod&&(a.contentLastMod=0);var c={url:escape(organicUrlFuns.rel_to_abs(a.src)),
timing:a.loadingTime,type:a.contentType,startTime:a.startTime,end_time:a.finishTime,cont_length:a.contentLength,last_mod:a.contentLastMod,code:404};organicArrays.timingArrayOfResult.push(c)}403==b.status&&(a.contentLength=b.getResponseHeader("Content-Length"),a.contentLength=a.contentLength.toString().split(" ").join(""),a.contentType=b.getResponseHeader("Content-Type"),a.contentType=a.contentType.toString().split(" ").join(""),a.contentLastMod=organic.ParseDateMod(b.getResponseHeader("Last-Modified")),
a.contentLength&&a.contentType&&a.startTime&&(a.loadingTime=a.finishTime-a.startTime,null==a.contentLastMod&&(a.contentLastMod=0),c={url:escape(organicUrlFuns.rel_to_abs(a.src)),timing:a.loadingTime,type:a.contentType,startTime:a.startTime,end_time:a.finishTime,cont_length:a.contentLength,last_mod:a.contentLastMod,code:403},organicArrays.timingArrayOfResult.push(c)));200==b.status&&(a.contentLength=b.getResponseHeader("Content-Length"),a.contentLength=a.contentLength.toString().split(" ").join(""),
a.contentType=b.getResponseHeader("Content-Type"),a.contentType=a.contentType.toString().split(" ").join(""),a.contentLastMod=organic.ParseDateMod(b.getResponseHeader("Last-Modified")),a.contentLength&&a.contentType&&a.startTime&&(a.loadingTime=a.finishTime-a.startTime,null===a.contentLastMod&&(a.contentLastMod=0),c={url:escape(organicUrlFuns.rel_to_abs(a.src)),timing:a.loadingTime,type:a.contentType,startTime:a.startTime,end_time:a.finishTime,cont_length:a.contentLength,last_mod:a.contentLastMod,
code:200},organicArrays.timingArrayOfResult.push(c)));304==b.status&&(a.contentLength=b.getResponseHeader("Content-Length"),a.contentLength=a.contentLength.toString().split(" ").join(""),a.contentType=b.getResponseHeader("Content-Type"),a.contentType=a.contentType.toString().split(" ").join(""),a.contentLastMod=organic.ParseDateMod(b.getResponseHeader("Last-Modified")),a.contentLength&&a.contentType&&a.startTime&&(a.loadingTime=a.finishTime-a.startTime,null==a.contentLastMod&&(a.contentLastMod=0),
c={url:escape(organicUrlFuns.rel_to_abs(a.src)),timing:a.loadingTime,type:a.contentType,startTime:a.startTime,end_time:a.finishTime,cont_length:a.contentLength,last_mod:a.contentLastMod,code:304},organicArrays.timingArrayOfResult.push(c)))}};b.open("HEAD",a.src,!0);b.send(null)}catch(c){organicArrays.errorListArray.push("Header")}}},NodeUpdateHandler:function(a){try{var b=a.target;-1==organicUrlFuns.rel_to_abs(b.src).indexOf(document.domain)&&organic.Setting.crossDomainXmlHttpReq?organic.ImageTimer(b.src):
organic.Timing.Start(b.src)}catch(c){organicArrays.errorListArray.push("NodeUpdateHandler")}},NodeErrorHandler:function(a){try{var b=a.target;b.finishTime=organic.StartTimer();organic.ReadXHRHeader(b)}catch(c){organicArrays.errorListArray.push("NodeErrorHandler")}},NodeAttributeHandler:function(a){try{var b=a.target.nodeName;if("src"==a.attrName&&"IMG"==b){var c=organic.StartTimer(),d=a.target;d.node_type="Dynamic";d.startTime=c}}catch(e){organicArrays.errorListArray.push("NodeAttributeHandler")}},
Session:{GenerateID:function(){function a(){return(65536*(1+Math.random())|0).toString(16).substring(1)}return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}},SCUserAgents:["Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)","Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.2)"],SCUserAgentSearch:function(){for(var a=0;a<organic.SCUserAgents.length;a++)if(organic.SCUserAgents[a]==navigator.userAgent)return!0;return-1!=navigator.userAgent.indexOf("SiteCon")?!0:!1},IfCrossDomain:function(){try{return"withCredentials"in
new XMLHttpRequest?!0:"undefined"!==typeof XDomainRequest?!0:!1}catch(a){return organicArrays.errorListArray.push("IFCrossDomain"),!1}},CrossDomainCracker:function(a,b){try{if(organic.ifCrossDomainPost()){var c;"Explorer"==organic.ClientSystemInfo().Browser?(c=new XDomainRequest,c.onload=function(){"stop-session"==c.responseText&&organic.Cookies.Stop()}):(c=new XMLHttpRequest,c.onreadystatechange=function(){4==c.readyState&&200==c.status&&"stop-session"==c.responseText&&organic.Cookies.Stop()});c.open("Post",
a,!0);c.send(b)}else{var d=document.createElement("script");d.type="text/javascript";organic.Tags.AppFinishTag(d);d.src=a+"?"+b;document.getElementsByTagName("head")[0].appendChild(d);d.onload=function(){d.src=""}}}catch(e){organicArrays.errorListArray.push("CrossDomainCracker")}},EndTimeUpdateHandler:function(a){try{document.createElement("img").src=a}catch(b){organicArrays.errorListArray.push("EndTimeUpdateHandler")}},String:{UrlCorrector:function(a){if(-1==a.toString().indexOf("http://")||-1==
a.toString().indexOf("https://"))return-1!=a.toString().indexOf("javascript")&&"/"==a.charAt(0)&&(a=a.toString().substring(1),a=document.URL.toString()+a),a},RemoveSpacesQuotations:function(a){try{a=a.replace(/^\s*|\s*$/g,""),a=a.replace(/['"]/g,"")}catch(b){organicArrays.errorListArray.push("RemoveSpacesQuotations")}finally{return a}}},Cookies:{Stop:function(a){var b=(new Date).getTime(),c=new Date;c.setTime(b+6E4*a);document.cookie="SE=t; expires="+c.toString()+"; path=/"},ifStop:function(){return organic.Cookies.Read("SE=")},
Write:function(a){try{var b=organic.Cookies.Read("SCOSN="),c=organic.Cookies.Read("SCOSID=");if(c&&a&&b){var d=c,e=parseInt(b)+1;organic.cookieSessionID=c;organic.cookieStepNum=b;var f=(new Date).getTime(),g=new Date;g.setTime(f+6E4*a);var h="; expires="+g.toString();document.cookie="SCOSID="+d+h+"; path=/";document.cookie="SCOSN="+e+h+"; path=/";return{sessionID:d,stepNum:e}}if(a)return d=organic.Session.GenerateID(),organic.cookieSessionID=d,organic.cookieStepNum=1,f=(new Date).getTime(),g=new Date,
g.setTime(f+6E4*a),h="; expires="+g.toString(),document.cookie="SCOSID="+d+h+"; path=/",document.cookie="SCOSN=1"+h+"; path=/",{sessionID:d,stepNum:1}}catch(k){organicArrays.errorListArray.push("Write")}},Read:function(a){try{var b=null;if(document.cookie){for(var c=document.cookie.split(";"),d=c.length,e=0;e<d;e++){for(var f=c[e];" "==f.charAt(0);)f=f.substring(1,f.length);0==f.indexOf(a)&&(b=f.substring(a.length,f.length))}return b}return null}catch(g){organicArrays.errorListArray.push("Read")}}},
Tags:{AppFinishTag:function(a){a.setAttribute("Organic",!0)},AppCheckTag:function(a){a.setAttribute("Organic",!1)},IsChecked:function(a){return null!=a.getAttribute("Organic")?!0:!1},IsCaptured:function(a){return"true"==organic.Tags.IsChecked(a).toString()?"true"==a.getAttribute("Organic").toString()?!0:!1:!1}},OrganicEvents:{AttachListener:function(a){"Explorer"!=organic.ClientSystemInfo().Browser?a.addEventListener("load",organic.OrganicEvents.ListenerHandler,!1):a.attachEvent("onload",organic.OrganicEvents.ListenerHandlerIE)},
ListenerHandlerIE:function(a){try{a=window.event||a;var b=a.srcElement||a.target;a="";if(void 0!==b&&null!=b&&(a=b.src,organic.Tags.AppFinishTag(b),organicArrays.endTimeArray[a]=organic.StartTimer(),organicArrays.startTimeArray[a])){var c={url:escape(organicUrlFuns.rel_to_abs(a)),timing:organicArrays.endTimeArray[a]-organicArrays.startTimeArray[a],type:b.tagName,startTime:organicArrays.startTimeArray[a],end_time:organicArrays.endTimeArray[a],cont_length:-1,last_mod:0,code:200};organicArrays.timingArrayOfResult.push(c)}}catch(d){organicArrays.errorListArray.push("ListenerHandlerIE")}},
ListenerHandler:function(a){try{var b="",c=a.target;if(void 0!==c&&(b=c.src,organic.Tags.AppFinishTag(c),organicArrays.endTimeArray[b]=organic.StartTimer(),organicArrays.startTimeArray[b])){var d={url:escape(organicUrlFuns.rel_to_abs(this.src)),timing:organicArrays.endTimeArray[b]-organicArrays.startTimeArray[b],type:c.tagName,startTime:organicArrays.startTimeArray[b],end_time:organicArrays.endTimeArray[b],cont_length:-1,last_mod:0,code:200};organicArrays.timingArrayOfResult.push(d)}}catch(e){organicArrays.errorListArray.push("ListenerHandler")}}},
CaptureLoadTime:function(a){try{organic.Tags.AppCheckTag(a),organic.OrganicEvents.AttachListener(a)}catch(b){organicArrays.errorListArray.push("CaptureLoadTime")}},ScriptTimer:function(a){var b=organic.Timing.CacheBuster(a),c=document.createElement("img");organic.Tags.AppFinishTag(c);c.src=b;a=a.split("?")[0];organicArrays.startTimeArray[a]||(organicArrays.startTimeArray[a]=organic.StartTimer(),c.onerror=function(){organicArrays.endTimeArray[a]=organic.StartTimer();if(organicArrays.startTimeArray[a]){var b=
{url:escape(organicUrlFuns.rel_to_abs(a)),timing:organicArrays.endTimeArray[a]-organicArrays.startTimeArray[a],type:"Script",startTime:organicArrays.startTimeArray[a],end_time:organicArrays.endTimeArray[a],cont_length:-1,last_mod:0,code:200};organicArrays.timingArrayOfResult.push(b)}else""!=a&&void 0!=a&&"undefined"!=a&&(isXmlEnabled?isCrossDomainEnabled||-1!=organicUrlFuns.rel_to_abs(a).indexOf(document.domain)?8<organicUrlFuns.rel_to_abs(a).indexOf(document.domain)&&!isCrossDomainEnabled?organic.ScriptTimer(a):
organic.Timing.Start(a):organic.ImageTimer(a):organic.ImageTimer(a))})},CSSTimer:function(a){var b=document.createElement("img");organic.Tags.AppFinishTag(b);b.src=a;a=a.split("?")[0];organicArrays.startTimeArray[a]||(organicArrays.startTimeArray[a]=organic.StartTimer(),b.onerror=function(){organicArrays.endTimeArray[a]=organic.StartTimer();if(organicArrays.startTimeArray[a]){var b={url:escape(organicUrlFuns.rel_to_abs(a)),timing:organicArrays.endTimeArray[a]-organicArrays.startTimeArray[a],type:"StyleSheet",
startTime:organicArrays.startTimeArray[a],end_time:organicArrays.endTimeArray[a],cont_length:-1,last_mod:0,code:200};organicArrays.timingArrayOfResult.push(b)}else""!=a&&void 0!=a&&"undefined"!=a&&(isXmlEnabled?isCrossDomainEnabled||-1!=organicUrlFuns.rel_to_abs(a).indexOf(document.domain)?8<organicUrlFuns.rel_to_abs(a).indexOf(document.domain)&&!isCrossDomainEnabled?organic.ScriptTimer(a):organic.Timing.Start(a):organic.ImageTimer(a):organic.ImageTimer(a))})},ImageTimer:function(a){try{var b=organic.Timing.CacheBuster(a),
c=document.createElement("img");organic.Tags.AppFinishTag(c);c.src=b;organicArrays.startTimeArray[a]||(organicArrays.startTimeArray[a]=organic.StartTimer(),c.onerror=function(b){organicArrays.endTimeArray[a]=organic.StartTimer();organicArrays.startTimeArray[a]?(b={url:escape(organicUrlFuns.rel_to_abs(a)),timing:organicArrays.endTimeArray[a]-organicArrays.startTimeArray[a],type:"Image",startTime:organicArrays.startTimeArray[a],end_time:organicArrays.endTimeArray[a],cont_length:-1,last_mod:0,code:0},
organicArrays.timingArrayOfResult.push(b)):""!=a&&void 0!=a&&"undefined"!=a&&(isXmlEnabled?isCrossDomainEnabled||-1!=organicUrlFuns.rel_to_abs(a).indexOf(document.domain)?8<organicUrlFuns.rel_to_abs(a).indexOf(document.domain)&&!isCrossDomainEnabled?organic.ScriptTimer(a):organic.Timing.Start(a):organic.ImageTimer(a):organic.ImageTimer(a))},c.onload=function(){organicArrays.endTimeArray[a]=organic.StartTimer();if(organicArrays.startTimeArray[a]){var b={url:escape(organicUrlFuns.rel_to_abs(a)),timing:organicArrays.endTimeArray[a]-
organicArrays.startTimeArray[a],type:"Image",startTime:organicArrays.startTimeArray[a],end_time:organicArrays.endTimeArray[a],cont_length:-1,last_mod:0,code:200};organicArrays.timingArrayOfResult.push(b)}else""!=a&&void 0!=a&&"undefined"!=a&&(isXmlEnabled?isCrossDomainEnabled||-1!=organicUrlFuns.rel_to_abs(a).indexOf(document.domain)?8<organicUrlFuns.rel_to_abs(a).indexOf(document.domain)&&!isCrossDomainEnabled?organic.ScriptTimer(a):organic.Timing.Start(a):organic.ImageTimer(a):organic.ImageTimer(a))})}catch(d){organicArrays.errorListArray.push("ImageTimer")}},
Nodes:{GetElement:function(a){try{var b=document.getElementsByTagName(a);if(0<b.length)for(a=0;a<b.length-1;a++)b[a].getAttribute("src")&&!1==organic.Tags.IsChecked(b[a])&&!organicArrays.startTimeArray[b[a].getAttribute("src")]&&(organicArrays.startTimeArray[b[a].getAttribute("src")]=organic.StartTimer(),organic.CaptureLoadTime(b[a]))}catch(c){organicArrays.errorListArray.push("GetElement")}},ScanUrlsIE:function(a,b){try{for(var c=[],d=0;d<document.all.length;d++){var e=document.all[d];if(1==e.nodeType){var f=
e.tagName;e.check=!1;var g="",h="",k="";if(!organic.Tags.IsCaptured(e)&&(e.getAttribute("src")&&(g=organic.String.UrlCorrector(e.getAttribute("src"))),e.getAttribute("type")&&(h=e.getAttribute("type")),e.href&&(k=e.getAttribute("href")),e.getAttribute("src")||e.getAttribute("href")))if("img"==f.toLowerCase())if(organic.Tags.AppFinishTag(e),e.getAttribute("src")&&organic.Setting.domUpdatingTiming&&organic.ImageHandler(e),a)if(b||-1!=organicUrlFuns.rel_to_abs(g).indexOf(document.domain))if(8<organicUrlFuns.rel_to_abs(g).indexOf(document.domain)&&
!b)organic.ScriptTimer(g);else{var l={url:g};c.push(l)}else organic.ImageTimer(g);else organic.ImageTimer(g);else"text/css"==h.toLowerCase()?(organic.Tags.AppFinishTag(e),a?-1!=organicUrlFuns.rel_to_abs(k).indexOf(document.domain)||b?8<organicUrlFuns.rel_to_abs(k).indexOf(document.domain)&&!b?organic.ScriptTimer(k):(l={url:k},c.push(l)):organic.CSSTimer(organic.Timing.CacheBuster(k)):organic.CSSTimer(organic.Timing.CacheBuster(k))):"script"==f.toLowerCase()&&!1==e.check&&h&&"text/javascript"==h.toLowerCase()&&
(organic.Tags.AppFinishTag(e),a?-1!=organicUrlFuns.rel_to_abs(g).indexOf(document.domain)||b?8<organicUrlFuns.rel_to_abs(g).indexOf(document.domain)&&!b?organic.ScriptTimer(g):(l={url:g},c.push(l)):organic.ScriptTimer(g):organic.ScriptTimer(g),e.check=!0)}}return c}catch(m){organicArrays.errorListArray.push("ScanUrlsIE")}},ScanCSSUrls:function(){try{if(document.getElementsByTagName("link"))for(var a=[],b=document.getElementsByTagName("link"),c=0;c<b.length;c++)if(!organic.Tags.IsCaptured(b[c])&&"stylesheet"==
b[c].rel.toLowerCase()&&!organicArrays.startTimeArray[b[c].href]){organic.Tags.AppFinishTag(b[c]);var d=b[c].href;if(null!=d&&void 0!=d){if(organic.Setting.crossDomainXmlHttpReq&&organic.Setting.isXMLTimingMethodEnabled){var e={url:d};a.push(e)}else organic.Setting.crossDomainXmlHttpReq||-1!=organicUrlFuns.rel_to_abs(d).indexOf(document.domain)?8<organicUrlFuns.rel_to_abs(d).indexOf(document.domain)?organic.ScriptTimer(d):(e={url:d},a.push(e)):organic.CSSTimer(organic.Timing.CacheBuster(d));organic.Setting.isXMLTimingMethodEnabled||
organic.CSSTimer(organic.Timing.CacheBuster(d))}}}catch(f){organicArrays.errorListArray.push("ScanCssUrl")}finally{return a}},ScanUrls:function(){var a=[];try{for(var b=document.getElementsByTagName("img"),c=0;c<b.length;c++)if(b[c].getAttribute("src")&&organic.Setting.domUpdatingTiming&&organic.ImageHandler(b[c]),!organic.Tags.IsCaptured(b[c])&&null!=b[c].src&&void 0!=b[c].src&&""!=b[c].src&&!organicArrays.startTimeArray[b[c].src]){if(organic.Setting.crossDomainXmlHttpReq&&organic.Setting.isXMLTimingMethodEnabled){var d=
{url:b[c].src};a.push(d)}else-1!=organicUrlFuns.rel_to_abs(b[c].src).indexOf(document.domain)||organic.Setting.crossDomainXmlHttpReq?8<organicUrlFuns.rel_to_abs(b[c].src).indexOf(document.domain)?organic.ScriptTimer(b[c].src):(d={url:b[c].src},a.push(d)):organic.ImageTimer(b[c].src);organic.Tags.AppFinishTag(b[c]);organic.Setting.isXMLTimingMethodEnabled||organic.ImageTimer(b[c].src)}for(var e=document.getElementsByTagName("script"),c=0;c<e.length;c++)organic.Tags.IsCaptured(e[c])||null==e[c].src||
void 0==e[c].src||""==e[c].src||organicArrays.startTimeArray[e[c].src]||(organic.Setting.crossDomainXmlHttpReq&&organic.Setting.isXMLTimingMethodEnabled?(d={url:e[c].src},a.push(d)):-1!=organicUrlFuns.rel_to_abs(e[c].src).indexOf(document.domain)||organic.Setting.crossDomainXmlHttpReq?8<organicUrlFuns.rel_to_abs(e[c].src).indexOf(document.domain)&&!organic.Setting.crossDomainXmlHttpReq?organic.ScriptTimer(e[c].src):(d={url:e[c].src},a.push(d)):organic.ScriptTimer(e[c].src),organic.Tags.AppFinishTag(e[c]),
organic.Setting.isXMLTimingMethodEnabled||organic.ScriptTimer(e[c].src))}catch(f){organicArrays.errorListArray.push("ScanUrls")}finally{return a}}},OrganicPolling:{StopPolling:function(){try{clearInterval(organic.SetLoopTimer)}catch(a){organicArrays.errorListArray.push("OrganicPolling")}},SetLoopTimer:function(){try{setInterval("organic.Nodes.GetElement('script')",30),setInterval("organic.Nodes.GetElement('img')",30)}catch(a){organicArrays.errorListArray.push("SetLoopTimer")}}},Process:{AnalyseDoc:function(){try{var a=
organic.Cookies.Write(organic.Setting.expireSetting);organic.cookieSessionID=a.sessionID;organic.cookieStepNum=a.stepNum}catch(b){organicArrays.errorListArray.push("AnalyseDoc")}},OnTimePlan:function(){try{organic.Setting.isBriefCaputreEnabled||organic.Setting.isEnableOnTimePlan&&organic.ifCrossDomainPost()&&organic.OrganicPolling.SetLoopTimer()}catch(a){organicArrays.errorListArray.push("OnTimePlan")}},BackUpPlan:function(){try{var a,b,c;if(!organic.Setting.isBriefCaputreEnabled&&organic.Setting.backupTimingEnabled&&
organic.ifCrossDomainPost())if(organic.Setting.isXMLTimingMethodEnabled){var d=organic.ClientSystemInfo().Browser,e;if("Firefox"==d||"Chrome"==d||"Safari"==d){a=organic.Nodes.ScanUrls();b=organic.Nodes.ScanCSSUrls();for(e=0;e<a.length;e++)"undefined"==a[e].url||void 0===a[e].url||organicArrays.endTimeArray[a[e].url]||organic.Timing.Start(a[e].url);if(0<b.length)for(e=0;e<b.length;e++)"undefined"==b[e].url||void 0===b[e].url||organicArrays.endTimeArray[a[e].url]||organic.Timing.Start(b[e].url)}if("Explorer"==
d)for(c=organic.Nodes.ScanUrlsIE(organic.Setting.isXMLTimingMethodEnabled,organic.Setting.crossDomainXmlHttpReq),e=0;e<c.length;e++)"undefined"==c[e].url||void 0===c[e].url||organicArrays.endTimeArray[c[e].url]||organic.Timing.Start(c[e].url)}else if("Explorer"==organic.ClientSystemInfo().Browser)organic.Nodes.ScanUrlsIE(organic.Setting.isXMLTimingMethodEnabled,organic.Setting.crossDomainXmlHttpReq);else if("Firefox"==organic.ClientSystemInfo().Browser||"Chrome"==organic.ClientSystemInfo().Browser||
"Safari"==organic.ClientSystemInfo().Browser)organic.Nodes.ScanUrls(),organic.Nodes.ScanCSSUrls()}catch(f){organicArrays.errorListArray.push("BackUpPlan-"+f)}}},Timing:{CacheBuster:function(a){try{return-1!=a.indexOf("?")?a=a+"&Axz="+organic.StartTimer():a+"?Axz="+organic.StartTimer()}catch(b){organicArrays.errorListArray.push("CacheBuster")}},Start:function(a){try{if(""!=a&&void 0!==a&&null!==a&&!organicArrays.startTimeArray[a]){var b=organic.OrganicRequest.Create(),c=organic.Timing.CacheBuster(a);
!1==organic.Setting.isWrapperEnable&&(b.onreadystatechange=function(){1==b.readyState&&(httpRequestStartTime=organic.StartTimer(),organicArrays.startTimeArray[a]=httpRequestStartTime);if(4==b.readyState&&b.status){httpRequestEndTime=organic.StartTimer();httpRequestLoadingTime=httpRequestEndTime-httpRequestStartTime;var c=b.getResponseHeader("Content-Type");if(c)var d=c.toString().split(" ").join("");if(c=b.getResponseHeader("Content-Length"))var g=c.toString().split(" ").join("");var h=organic.ParseDateMod(b.getResponseHeader("Last-Modified"));
a==document.location.href?(c&&(organicDocInfo.currentDocumentSize=c.toString().split(" ").join("")),organic.currentDcoumentLastMod=h,organicDocInfo.currentDocumentRequestTime=httpRequestLoadingTime):(null==h&&(h=0),d={url:escape(organicUrlFuns.rel_to_abs(a)),timing:httpRequestLoadingTime,type:d,startTime:httpRequestStartTime,end_time:httpRequestEndTime,cont_length:g,last_mod:h,code:b.status},organicArrays.timingArrayOfResult.push(d))}});b.open("GET",c,!0);b.send(null)}}catch(d){organicArrays.errorListArray.push("Start")}}},
updateLoadingTime:function(){try{organic.currentPageLoadingTime=(new Date).getTime()}catch(a){organicArrays.errorListArray.push("UpdateLoadingTime")}},updateLeaveTime:function(){try{organic.clientLeaveTime=(new Date).getTime()}catch(a){organicArrays.errorListArray.push("updateLeaveTime")}}};function InitializeSCScript(){organic.updateLoadingTime();organic.updateLeaveTime();"t"!=organic.Cookies.ifStop()&&(setInterval(organic.Process.BackUpPlan,3E3),organic.OrganicPolling.StopPolling())}
var OrganicFormData={retrieveHTML:function(){try{xmlhttp=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP"),xmlhttp.onreadystatechange=function(){if(4==xmlhttp.readyState&&200==xmlhttp.status){xmlhttp.getResponseHeader("Last-Modified");var a=xmlhttp.responseText;if(organic.ifCrossDomainPost())OrganicFormData.submitHTMLCodeCrossDomain(a);else{var c=[];if(1E3>=a.length)c.push(a);else for(;1E3<a.length;){var d=a.substring(0,1E3),a=a.substring(1E3);c.push(d);if(1E3>a.length){c.push(a);
break}}OrganicFormData.submitHTMLCode(c)}}},xmlhttp.open("GET",document.location,!0),xmlhttp.send()}catch(a){organicArrays.errorListArray.push("RetrieveHtml")}},retrieveForm:function(){try{var a=document.forms;if(a)for(var b=document.forms.length,c=0;c<b;c++){var d=a[c];d&&OrganicFormData.addFormEventListener(d)}}catch(e){organicArrays.errorListArray.push("RetrieveForm")}},retrieveFormData:function(a){try{var b=a||window.event;a="";if(b.target){var c=b.target;a=c.name+","+c.value+","+c.type}organic.ifCrossDomainPost()?
OrganicFormData.submitFormDataCrossDomain(a):OrganicFormData.submitFormData(a)}catch(d){organicArrays.errorListArray.push("RetrieveFormData")}},addFormEventListener:function(a){try{a.addEventListener?a.addEventListener("change",OrganicFormData.retrieveFormData,!1):a.attachEvent?a.attachEvent("onchange",OrganicFormData.retrieveFormData):a.onchange&&(a.onchange=OrganicFormData.retrieveFormData)}catch(b){organicArrays.errorListArray.push("addFormEventListener")}},submitFormDataCrossDomain:function(a){try{var b=
organic.packetStringHeader();organic.packetId++;b=organic.jsonBuilder.jsonFormDataBuilder(b,escape(a));b=organic.jsonBuilder.jsonPacketNumberBuilder(b,organic.packetId);0<organicArrays.timingArrayOfResult.length&&(b=organic.jsonBuilder.jsonTimingResultBuilder(b,organicArrays.timingArrayOfResult));b=JSON.stringify(b);organic.CrossDomainCracker(organic.Setting.serverHandler(),b)}catch(c){organicArrays.errorListArray.push("submitFormData")}},submitFormData:function(a){try{var b=organic.packetStringHeader();
organic.packetId++;organic.CrossDomainCracker(organic.Setting.serverHandler()+"?"+b+"&FD="+escape(a)+"&PacketId="+organic.packetId)}catch(c){organicArrays.errorListArray.push("submitFormData")}},submitHTMLCode:function(a){try{for(var b=a.length,c=organic.packetStringHeader(),d=0;d<b;d++)organic.packetId++,organic.CrossDomainCracker(organic.Setting.serverHandler(),c+"&HD="+escape(a[d])+"&PacketId="+organic.packetId)}catch(e){organicArrays.errorListArray.push("submitHTMLCode")}},submitHTMLCodeCrossDomain:function(a){try{var b=
organic.packetStringHeader();organic.packetId++;b=organic.jsonBuilder.jsonHtmlDataBuilder(b,escape(a));b=organic.jsonBuilder.jsonPacketNumberBuilder(b,organic.packetId);0<organicArrays.timingArrayOfResult.length&&(b=organic.jsonBuilder.jsonTimingResultBuilder(b,organicArrays.timingArrayOfResult));b=JSON.stringify(b);organic.CrossDomainCracker(organic.Setting.serverHandler(),b)}catch(c){organicArrays.errorListArray.push("submitHTMLCrossDomain")}},documentLastModified:function(){return document.lastModified},
retrieveFormAndHtml:function(){try{window.addEventListener?(organic.Setting.isHtmlCaptureEnabled&&organic.ifCrossDomainPost()&&window.addEventListener("load",OrganicFormData.retrieveHTML,!1),organic.Setting.isFormCaptureEnabled&&organic.ifCrossDomainPost()&&window.addEventListener("load",OrganicFormData.retrieveForm,!1)):window.attachEvent?(organic.Setting.isHtmlCaptureEnabled&&organic.ifCrossDomainPost()&&window.attachEvent("onload",OrganicFormData.retrieveHTML),organic.Setting.isFormCaptureEnabled&&
organic.ifCrossDomainPost()&&window.attachEvent("onload",OrganicFormData.retrieveForm)):window.onload&&(organic.Setting.isHtmlCaptureEnabled&&organic.ifCrossDomainPost()&&(window.onload=OrganicFormData.retrieveHTML),organic.Setting.isFormCaptureEnabled&&organic.ifCrossDomainPost()&&(window.onload=OrganicFormData.retrieveForm))}catch(a){organicArrays.errorListArray.push("OrganicFormMain")}}};
try{var SC_Organic_Wrappers={organicXMLWrapper:function(){try{if(organic.Setting.isWrapperEnable&&window.XMLHttpRequest){var a=window.XMLHttpRequest;window.XMLHttpRequest=function(){var b=new a;b.oldOpen=b.open;b.open=function(a,e,f,g,h){this.onreadystatechange=organicListeners.addlistener;organicArrays.startTimeArray[e]=(new Date).getTime();b.url=e;this.oldOpen(a,e,f,g,h)};return b}}}catch(b){organicArrays.errorListArray.push("Wrapper")}}};SC_Organic_Wrappers.organicXMLWrapper();window.opera&&(opera.setOverrideHistoryNavigationMode("compatible"),
history.navigationMode="compatible");window.addEventListener?window.addEventListener("load",InitializeSCScript,!1):window.attachEvent?window.attachEvent("onload",InitializeSCScript):window.onLoad&&(window.onload=InitializeSCScript);var currentRootUrl=organic.rootUrl;organic.Setting.isXMLTimingMethodEnabled&&organic.OrganicRequest.Document(currentRootUrl);organic.Process.OnTimePlan();organic.Process.AnalyseDoc();organic.DOM.DOMReady();setInterval(organic.ReadyToSubmit,1E5)}catch(err$$67){errorToString=
"Main",organicArrays.errorListArray.push(errorToString)};;

/* file-end: js/ads/axz.min.js 
----------------------------------------------------------------------------------*/
