document.write("<"+"script type=\"text/javascript\" src=\"http://cdn.hadj7.adjuggler.net/banners/rtb/rtb_8.0.5_2.js\"><"+"/script>\n");
document.write("<"+"script type=\"text/javascript\">\n");
document.write("(function () {\n");
document.write("function show_ad(rtb) {\n");
document.write("var request = {\n");
document.write("'aj_ecpm' : 0\n");
document.write("};\n");
document.write("rtb.script_url = 'http://cdn.hadj7.adjuggler.net/banners/';\n");
document.write("rtb.confirm_banner_url = 'http://mshakers.rotator.hadj7.adjuggler.net/servlet/ajrotator/252066/0/impr?ajkey=V128654D4D1J-573J8020L22099518382114CL305373L305372QL221013QQP0G01G0G0Q0AD2F15700000101000061';\n");
document.write("rtb.ad_height = '600';\n");
document.write("rtb.above_the_fold_threshold = 0.5;\n");
document.write("rtb.pubmatic.server_url = 'http://bid.pubmatic.com/AdServer/AdServerServlet';\n");
document.write("request['pubmatic_request'] = {\n");
document.write("'price_floor' : 0.3,\n");
document.write("'pubId' : 29297,\n");
document.write("'siteId' : 31882,\n");
document.write("'adId' : 31407,\n");
document.write("'kadwidth' : 160,\n");
document.write("'kadheight' : 600,\n");
document.write("'kltstamp' : '2013-10-12+16%3A48%3A23',\n");
document.write("'price_floor_offset' : 0,\n");
document.write("'pageURL' : 'http%3A%2F%2Fib.adnxs.com',\n");
document.write("'kadpageurl': 'http%3A%2F%2Fib.adnxs.com',\n");
document.write("'ranreq' : 0.04106949696269724\n");
document.write("};\n");
document.write("rtb.openrtb.server_url = 'http://yorick.adjuggler.net/openrtb/1.0/json';\n");
document.write("request['openrtb_request'] = {\n");
document.write("'zone' : 220995,\n");
document.write("'pub' : 252050,\n");
document.write("'adspot' : 252066,\n");
document.write("'cluster' : 'hadj7',\n");
document.write("'country' : 'at',\n");
document.write("'price_floor_offset' : 0,\n");
document.write("'rnd' : 0.45060542043217855,\n");
document.write("'price_floor' : 0,\n");
document.write("'url' : 'http%3A%2F%2Fib.adnxs.com%2Ftt%3Fid%3D1804549%26size%3D160x600%26referrer%3Dhttp%253A%252F%252Fpustoj-zhurnal.livejournal.com%252F51210.html',\n");
document.write("'width' : 160,\n");
document.write("'height' : 600\n");
document.write("};\n");
document.write("function show_aj_ad() {\n");
document.write("document.write(\"<"+"\"+\"html>\\n\");\n");
document.write("document.write(\"<"+"\"+\"head>\\n\");\n");
document.write("document.write(\"<"+"\"+\"title><"+"\"+\"/title>\\n\");\n");
document.write("document.write(\"<"+"\"+\"/head>\\n\");\n");
document.write("document.write(\"<"+"\"+\"body>\\n\");\n");
document.write("document.write(\"<"+"\"+\"script  src=\\\"http://tag.contextweb.com/TagPublish/getjs.aspx?action=VIEWAD&cwrun=200&cwadformat=160X600&cwpid=557432&cwwidth=160&cwheight=600&cwpnet=1&cwtagid=171719\\\"><"+"\"+\"/script>\\n\");\n");
document.write("document.write(\"<"+"\"+\"/body>\\n\");\n");
document.write("document.write(\"<"+"\"+\"/html>\");\n");
document.write("\n");
document.write("}\n");
document.write("rtb.callAllSources(request, show_aj_ad);\n");
document.write("}\n");
document.write("/* Since IE doesn't guarantee JS execution order, we need to store this ad until rtb.js was successfully loaded */\n");
document.write("if (window.adjuggler && window.adjuggler.rtb) {\n");
document.write("show_ad(window.adjuggler.rtb);\n");
document.write("} else {\n");
document.write("if (!window.adjuggler) {\n");
document.write("window.adjuggler = {\n");
document.write("waiting_ads : []\n");
document.write("};\n");
document.write("}\n");
document.write("window.adjuggler.waiting_ads.push(show_ad);\n");
document.write("}\n");
document.write("})();\n");
document.write("<"+"/script>");
